name:                 king-game
version:              0.1.0.0
visibility:           public
id:                   king-game-0.1.0.0-inplace
key:                  king-game-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2021 Julio Raffaine
maintainer:           julio.loxas@gmail.com
author:               Julio Raffaine
homepage:             https://bitbucket.org/raffaine/cardgamehall/
description:
    Client and Server for my King Card Game, info on <http://elloxas.blogspot.com>

abi:                  inplace
exposed:              True
exposed-modules:      GameRules KingClient KingTypes ServerLogic
import-dirs:
    /mnt/c/dev/repos/king-cardgame/Clients/haskell/king-game-client/dist-newstyle/build/aarch64-linux/ghc-9.6.7/king-game-0.1.0.0/build

library-dirs:
    /mnt/c/dev/repos/king-cardgame/Clients/haskell/king-game-client/dist-newstyle/build/aarch64-linux/ghc-9.6.7/king-game-0.1.0.0/build

library-dirs-static:
    /mnt/c/dev/repos/king-cardgame/Clients/haskell/king-game-client/dist-newstyle/build/aarch64-linux/ghc-9.6.7/king-game-0.1.0.0/build

dynamic-library-dirs:
    /mnt/c/dev/repos/king-cardgame/Clients/haskell/king-game-client/dist-newstyle/build/aarch64-linux/ghc-9.6.7/king-game-0.1.0.0/build

data-dir:
    /mnt/c/dev/repos/king-cardgame/Clients/haskell/king-game-client/.

hs-libraries:         HSking-game-0.1.0.0-inplace
depends:
    base-4.18.3.0 bytestring-0.11.5.4 containers-0.6.7
    json-0.11-5aa1c81b0b8b0ac5ba68208774135ff8b83661abaa729d3a22107a53bcafc24d
    mtl-2.3.1
    split-0.2.5-ad0973e6da51abf4063dcfdc6f801fbc1982e4ab1e2dee5e55520789b5a0588f
    stm-2.5.1.0
    zeromq4-haskell-0.8.0-304179e96dcadb8c4696cd570245e073caed070095f7ebe34eba35a79456ed86

haddock-interfaces:
    /mnt/c/dev/repos/king-cardgame/Clients/haskell/king-game-client/dist-newstyle/build/aarch64-linux/ghc-9.6.7/king-game-0.1.0.0/doc/html/king-game/king-game.haddock

haddock-html:
    /mnt/c/dev/repos/king-cardgame/Clients/haskell/king-game-client/dist-newstyle/build/aarch64-linux/ghc-9.6.7/king-game-0.1.0.0/doc/html/king-game
